"""Initial registry population for the first vertical slice."""

from red_team.registry.registry import ProvenanceRegistry
from red_team.schemas.calibration import (
    CalibrationDefinition,
    FeaturePairCalibration,
    FeatureType,
    MarginalCalibrationConfig,
    MetricType,
)
from red_team.schemas.provenance import (
    DatasetSource,
    DatasetSourceType,
    FeatureProvenance,
    ProvenanceTier,
    ReferenceStatistic,
)

def build_first_slice_registry() -> ProvenanceRegistry:
    """Populate the registry with the initial hackathon configuration."""

    # -----------------------------------------------------------------------
    # 1. Datasets
    # -----------------------------------------------------------------------
    ds_paysim = DatasetSource(
        id="paysim_v1",
        name="PaySim: A financial mobile money simulator for fraud detection",
        source_url="https://www.kaggle.com/datasets/ealaxi/paysim1",
        source_type=DatasetSourceType.SYNTHETIC_RESEARCH_DATASET,
        access_method="Kaggle Download",
        license="CC BY 4.0",
        license_url="https://creativecommons.org/licenses/by/4.0/",
        redistribution_allowed=True,
        commercial_use_allowed=True,
        citation_required=True,
        raw_storage_policy="local_only",
        known_limitations="Synthetic data generated by a simulator; lacks real complex behavioral nuances like genuine account takeover sequences.",
        notes="Primary source for transaction dynamics and amounts.",
    )

    ds_ieee = DatasetSource(
        id="ieee_cis_fraud",
        name="IEEE-CIS Fraud Detection",
        source_url="https://www.kaggle.com/c/ieee-fraud-detection",
        source_type=DatasetSourceType.REAL_WORLD_PRODUCTION,
        access_method="Kaggle Competition Agreement",
        license="Kaggle Competition Rules",
        license_url="https://www.kaggle.com/c/ieee-fraud-detection/rules",
        redistribution_allowed=False,
        commercial_use_allowed=False,
        citation_required=True,
        raw_storage_policy="local_only",
        known_limitations="Limited visibility into full user sessions; device data is hashed/obfuscated.",
        notes="Primary source for device and identity characteristics.",
    )

    datasets = [ds_paysim, ds_ieee]

    # -----------------------------------------------------------------------
    # 2. Features
    # -----------------------------------------------------------------------
    features = [
        # Learned features (Tier 1)
        FeatureProvenance(
            feature_name="transaction_amount",
            entity="transaction",
            data_type="numerical",
            provenance_tier=ProvenanceTier.TIER_1_LEARNED,
            source_datasets=["paysim_v1"],
            source_fields=["amount"],
            derivation_method="Empirical distribution fitting from PaySim transaction amounts.",
            required_for_world_model=True,
        ),
        FeatureProvenance(
            feature_name="transaction_type",
            entity="transaction",
            data_type="categorical",
            provenance_tier=ProvenanceTier.TIER_1_LEARNED,
            source_datasets=["paysim_v1"],
            source_fields=["type"],
            derivation_method="Categorical frequency calculation from PaySim transaction types.",
            required_for_world_model=True,
        ),
        FeatureProvenance(
            feature_name="device_type",
            entity="device",
            data_type="categorical",
            provenance_tier=ProvenanceTier.TIER_1_LEARNED,
            source_datasets=["ieee_cis_fraud"],
            source_fields=["DeviceInfo", "DeviceType"],
            derivation_method="Extracted and normalized categorical mapping from IEEE-CIS device attributes.",
            required_for_world_model=True,
        ),
        
        # Derived features (Tier 2)
        FeatureProvenance(
            feature_name="customer_typical_amount",
            entity="customer",
            data_type="numerical",
            provenance_tier=ProvenanceTier.TIER_2_DERIVED,
            source_datasets=["paysim_v1"],
            source_fields=["amount", "nameOrig"],
            derivation_method="Calculated as the mean of transaction amounts grouped by customer.",
            required_for_world_model=True,
        ),
        
        # Domain Modeled features (Tier 3)
        FeatureProvenance(
            feature_name="beneficiary_relationship_age",
            entity="relationship",
            data_type="temporal",
            provenance_tier=ProvenanceTier.TIER_3_DOMAIN_MODELED,
            generation_method="Simulated using an exponential distribution based on customer account age.",
            required_for_world_model=True,
            assumptions=[
                "Public datasets do not contain long-term beneficiary link histories.",
                "Most beneficiaries are added early in the account lifecycle."
            ],
        ),
    ]

    # -----------------------------------------------------------------------
    # 3. Calibration Definitions
    # -----------------------------------------------------------------------
    cal_def = CalibrationDefinition(
        marginal_configs=[
            MarginalCalibrationConfig(
                feature_name="transaction_amount",
                feature_type=FeatureType.NUMERICAL,
                metric=MetricType.KS_STATISTIC,
            ),
            MarginalCalibrationConfig(
                feature_name="transaction_type",
                feature_type=FeatureType.CATEGORICAL,
                metric=MetricType.CATEGORICAL_FREQUENCY,
            ),
            MarginalCalibrationConfig(
                feature_name="customer_typical_amount",
                feature_type=FeatureType.NUMERICAL,
                metric=MetricType.WASSERSTEIN,
            ),
        ],
        pair_configs=[
            FeaturePairCalibration(
                feature_a="transaction_amount",
                feature_b="transaction_type",
                feature_types=(FeatureType.NUMERICAL, FeatureType.CATEGORICAL),
                metric=MetricType.MUTUAL_INFORMATION,
                reason="Different transaction types (e.g. TRANSFER vs CASH_OUT) have distinct amount distributions in PaySim.",
            )
        ]
    )
    calibration_definitions = [cal_def]

    # -----------------------------------------------------------------------
    # 4. Reference Statistics
    # -----------------------------------------------------------------------
    ref_stats = [
        ReferenceStatistic(
            id="stat_paysim_fraud_rate",
            statistic_name="paysim_global_fraud_rate",
            value=0.0013,  # 0.13%
            source_dataset_id="paysim_v1",
            source="PaySim Paper",
            citation="Lopez-Rojas et al. (2016)",
            statistic_definition="Global percentage of transactions marked as isFraud.",
            externally_reported=True,
        )
    ]

    # -----------------------------------------------------------------------
    # Build and validate registry
    # -----------------------------------------------------------------------
    return ProvenanceRegistry(
        datasets=datasets,
        features=features,
        calibration_definitions=calibration_definitions,
        reference_statistics=ref_stats,
    )
